# Generated by Django 2.0.2 on 2018-04-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20180416_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='county',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
